version: 2.1

jobs:
  build-medium:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - run:
          name: Login to Docker Hub
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Build multiarch docker image and push
          command: |
            docker build -t nikopole/plextranscoder .
            docker tag httpd nikopole/plextranscoder:latest
            docker push nikopole/plextranscoder

workflows:
  build:
    jobs:
      - build-medium